### ISSUE TITLE
Is it possible to change bg color of ok-button?

### ISSUE THREAD

**Issue by Fabijanec** [usemodal-vue3/usemodal-vue3#1]
I tried to change it with custom css like :
.modal-vue3-footer-ok{
    background-color: black;
}
and
.modal-vue3-content :deep(.modal-vue3-footer-ok) {
    background-color: black;
}
What am I doing wrong ? Please help :)

**Comment by pageignore** [comment]
Yes, you can customize the css styles of the button. But you can't write the style in the `<style scoped>` of the single file, but in the externally imported css file.
In order to ensure that there will be no conflicts, it is recommended to wrap another layer of class like:
```html
<div class="modal-bg-red">
  <Modal v-model:visible="isVisible">
    <div>your content...</div>
  </Modal>
</div>
```
or
```html
<Modal modalClass="modal-bg-red" v-model:visible="isVisible">
    <div>your content...</div>
</Modal>
```
style.css
```css
.modal-bg-red .modal-vue3-footer-ok{
    background-color: red !important;
}
```

**Comment by Fabijanec** [comment]
Thank you very much :)
